import type { Metadata } from "next";
import { onest } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Церква Христа-Спасителя",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`${onest.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
